### ISSUE TITLE
 this._input.match is not a function -> match = this._input.match(this.rules[rules[i]]); 

### ISSUE THREAD

**Issue by hinderberg** [quirkey/sammy#118]
Sammy does not work correctly with jQuery 1.7 and Firefox.

To fix the issue: go to the load: function and replace dataType: is_json ? 'json' : null, with dataType: is_json ? 'json' : 'text', in the ajax call.
